config/routes.rb
Bourbon::Application.routes.draw do
 
  resources :categories

  get "distilleries/all"

  resources :whiskeys
  resources :distilleries

  root :to => redirect("/whiskeys")  

end

app/models/whiskey.rb
class Whiskey < ActiveRecord::Base
  belongs_to :distillery
  belongs_to :category

  accepts_nested_attributes_for :distillery, { 
  #  :allow_destroy => true,
    :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
  }
  accepts_nested_attributes_for :category, { 
  #  :allow_destroy => true,
    :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
  }

  attr_accessible :description, :distillery, :name, :distillery_attributes, :category, :category_attributes

  validates :description, :presence =>true
  validates :name, :presence =>true

end

app/controllers/whiskeys_controller.rb
class WhiskeysController < ApplicationController
  # GET /whiskeys
  # GET /whiskeys.json
  def index
    @whiskeys = Whiskey.find(:all, :order => :name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @whiskeys }
      format.xml { render :xml => @whiskeys }
    end
  end

  # GET /whiskeys/1
  # GET /whiskeys/1.json
  def show
    @whiskey = Whiskey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @whiskey }
      format.xml { render :xml => @whiskey }
    end
  end

  # GET /whiskeys/new
  # GET /whiskeys/new.json
  def new
    @whiskey = Whiskey.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @whiskey }
      format.xml { render :xml => @whiskey }
    end
  end

  # GET /whiskeys/1/edit
  def edit
    @whiskey = Whiskey.find(params[:id])
  end

  # POST /whiskeys
  # POST /whiskeys.json
  def create
    whiskeyParams = params[:whiskey]

    if !whiskeyParams.has_key?(:distillery) and whiskeyParams.has_key?(:distillery_id)
      distillery = Distillery.find(whiskeyParams[:distillery_id])
      whiskeyParams[:distillery] = distillery
      whiskeyParams.delete(:distillery_id)
    end

    if !whiskeyParams.has_key?(:category) and whiskeyParams.has_key?(:category_id)
      category = Category.find(whiskeyParams[:category_id])
      whiskeyParams[:category] = category
      whiskeyParams.delete(:category_id)
    end

    @whiskey = Whiskey.new(whiskeyParams)

    respond_to do |format|
      if @whiskey.save
        format.html { redirect_to @whiskey, :notice => 'Whiskey was successfully created.' }
        format.json { render :json => @whiskey, :status => :created, :location => @whiskey }
        format.xml { render :xml => @whiskey, :status => :created, :location => @whiskey }
      else
        format.html { render :action => "new" }
        format.json { render :json => @whiskey.errors, :status => :unprocessable_entity }
        format.xml { render :xml => @whiskey.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /whiskeys/1
  # PUT /whiskeys/1.json
  def update
    @whiskey = Whiskey.find(params[:id])

    respond_to do |format|
      whiskeyParams = params[:whiskey]

      if !whiskeyParams.has_key?(:distillery) and whiskeyParams.has_key?(:distillery_id)
        distillery = Distillery.find(whiskeyParams[:distillery_id])
        whiskeyParams[:distillery] = distillery
        whiskeyParams.delete(:distillery_id)
      end

      if !whiskeyParams.has_key?(:category) and whiskeyParams.has_key?(:category_id)
        category = Category.find(whiskeyParams[:category_id])
        whiskeyParams[:category] = category
        whiskeyParams.delete(:category_id)
      end

      if @whiskey.update_attributes(whiskeyParams)
        format.html { redirect_to @whiskey, :notice => 'Whiskey was successfully updated.' }
        format.json { head :no_content }
        format.xml { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @whiskey.errors, :status => :unprocessable_entity }
        format.xml { render :xml => @whiskey.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /whiskeys/1
  # DELETE /whiskeys/1.json
  def destroy
    @whiskey = Whiskey.find(params[:id])
    @whiskey.destroy

    respond_to do |format|
      format.html { redirect_to whiskeys_url }
      format.json { head :no_content }
      format.xml { head :no_content }
    end
  end
end

app/helpers/whiskeys_helper.rb
module WhiskeysHelper

  def setup_whiskey(whiskey)
    if whiskey.distillery == nil
      whiskey.build_distillery
    end
    if whiskey.category == nil
      whiskey.build_category
    end
    return whiskey
  end

  def get_distilleries_to_id_hash
    distilleries = Distillery.find(:all, :order => :name)
    dists_to_id = Hash.new
    distilleries.each do |dist|
       dists_to_id[dist] = dist.id
    end
    return dists_to_id
  end

  def get_categories_to_id_hash
    categories = Category.find(:all, :order => :name)
    cats_to_id = Hash.new
    categories.each do |cat|
      cats_to_id[cat] = cat.id
    end
    return cats_to_id
  end
end

app/views/whiskeys/_form.html.erb
<%= form_for setup_whiskey(@whiskey) do |f| %>
  <% if @whiskey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@whiskey.errors.count, "error") %> prohibited this whiskey from being saved:</h2>

      <ul>
      <% @whiskey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :distillery_id, :Distillery %><br />
    <%= f.select :distillery_id, get_distilleries_to_id_hash %>
  </div>

  <div class="field">
    <%= f.label :category_id, :Category %><br />
    <%= f.select :category_id, get_categories_to_id_hash %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/whiskeys/_whiskey.html.erb
<div class="whiskey-div-main">
<p>
<span class="whiskey-name"><b><%= link_to whiskey.name, whiskey %></b></span><br/>
<span class="whiskey-distillery">Distillery: 
<% if whiskey.distillery != nil %>
<%= link_to whiskey.distillery.name, whiskey.distillery %>
<% else %>
<%= :Unknown %>
<% end %>
</span><br/>
<span class="whiskey-distillery">Category: 
<% if whiskey.category != nil %>
<%= link_to whiskey.category.name, whiskey.category %>
<% else %>
<%= :Unknown %>
<% end %>
</span>
</p>
<p><%= whiskey.description %></p>

</div>

app/views/whiskeys/edit.html.erb
<h1>Editing whiskey</h1>

<%= render 'form' %>

<%= link_to 'Show', @whiskey %> |
<%= link_to 'Back', whiskeys_path %>

app/views/whiskeys/index.html.erb
<h1>Whiskeys</h1>

<table>
  <% @whiskeys.each do |whiskey| %>
  <tr>
    <%= render whiskey %>
  </tr>
  <% end %>
</table>

app/views/whiskeys/new.html.erb
<h1>New whiskey</h1>

<%= render 'form' %>

<%= link_to 'Back', whiskeys_path %>

app/views/whiskeys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @whiskey.name %>
</p>

<p>
  <b>Distillery:</b>
  <%= @whiskey.distillery %>
</p>

<p>
  <b>Category:</b>
  <%= @whiskey.category %>
</p>

<p>
  <b>Description:</b>
  <%= @whiskey.description %>
</p>


<%= link_to 'Edit', edit_whiskey_path(@whiskey) %> |
<%= link_to 'Back', whiskeys_path %> | 
<%= link_to 'Delete', whiskey_path(@whiskey), { :method => :delete }  %>