config/routes.rb
Bourbon::Application.routes.draw do
 
  resources :categories

  get "distilleries/all"

  resources :whiskeys
  resources :distilleries

  root :to => redirect("/whiskeys")  

end

app/models/distillery.rb
class Distillery < ActiveRecord::Base
  attr_accessible :name

  has_many :whiskeys

  validates :name, { :presence => :true, :uniqueness => true }

  def to_s
    return self.name
  end

end

app/controllers/distilleries_controller.rb
class DistilleriesController < ApplicationController
  # GET /distilleries
  # GET /distilleries.json
  def index
    @distilleries = Distillery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @distilleries }
    end
  end

  # GET /distilleries/1
  # GET /distilleries/1.json
  def show
    @distillery = Distillery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @distillery }
    end
  end

  # GET /distilleries/new
  # GET /distilleries/new.json
  def new
    @distillery = Distillery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @distillery }
    end
  end

  # GET /distilleries/1/edit
  def edit
    @distillery = Distillery.find(params[:id])
  end

  # POST /distilleries
  # POST /distilleries.json
  def create
    @distillery = Distillery.new(params[:distillery])

    respond_to do |format|
      if @distillery.save
        format.html { redirect_to @distillery, :notice => 'Distillery was successfully created.' }
        format.json { render :json => @distillery, :status => :created, :location => @distillery }
      else
        format.html { render :action => "new" }
        format.json { render :json => @distillery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /distilleries/1
  # PUT /distilleries/1.json
  def update
    @distillery = Distillery.find(params[:id])

    respond_to do |format|
      if @distillery.update_attributes(params[:distillery])
        format.html { redirect_to @distillery, :notice => 'Distillery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @distillery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /distilleries/1
  # DELETE /distilleries/1.json
  def destroy
    @distillery = Distillery.find(params[:id])
    @distillery.destroy

    respond_to do |format|
      format.html { redirect_to distilleries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/distilleries_helper.rb
module DistilleriesHelper
end

app/views/distilleries/_form.html.erb
<%= form_for(@distillery) do |f| %>
  <% if @distillery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@distillery.errors.count, "error") %> prohibited this distillery from being saved:</h2>

      <ul>
      <% @distillery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/distilleries/edit.html.erb
<h1>Editing distillery</h1>

<%= render 'form' %>

<%= link_to 'Show', @distillery %> |
<%= link_to 'Back', distilleries_path %>

app/views/distilleries/index.html.erb
<h1>Distilleries</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @distilleries.each do |distillery| %>
  <tr>
    <td><%= distillery.name %></td>
    <td><%= link_to 'Show', distillery %></td>
    <td><%= link_to 'Edit', edit_distillery_path(distillery) %></td>
    <td><%= link_to 'Delete', distillery, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Distillery', new_distillery_path %>

app/views/distilleries/new.html.erb
<h1>New distillery</h1>

<%= render 'form' %>

<%= link_to 'Back', distilleries_path %>

app/views/distilleries/show.html.erb
<p id="notice"><%= notice %></p>

<div>
<h1 style="display:inline;"><%= @distillery.name %> Whiskeys</h1>
<%= link_to 'Edit', edit_distillery_path(@distillery) %> 
</div><br/>

<% whiskeys = @distillery.whiskeys %>
<table>
  <% whiskeys.each do |whiskey| %>
  <tr>
    <%= render whiskey %>
  </tr>
  <% end %>
</table>